ARG BASE_IMAGE=busybox:1.37.0-glibc@sha256:6f1b51ce286ec478764ecaef269d9188e71b9fdd1f907670abd38549baf8dabe

# hadolint ignore=DL3006
FROM ${BASE_IMAGE}
LABEL maintainer="DeadNews <deadnewsgit@gmail.com>"

USER nobody:nobody
HEALTHCHECK NONE

CMD ["echo", "Hello, World!"]
