name: Push Tag

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  push-tag:
    name: Push Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dependency Review
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a "v1" -m "auto push tag"
          git push origin "v1"
