name: Push Tag

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  push-tag:
    name: Push Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Push Tag
        run: |
          git tag -a "v1" -m "auto push tag" --force
          git push origin "v1" --force
